name: Azure Static Web Apps CI/CD

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment
  deployment:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: create index.html and commit to the main branch
        #"tree --help" for help on command params
        run: |
          sudo apt install tree
          pwd
          ls -l
          echo 'creating index.html file...'
          tree -H '.' -L 3 -C -r --noreport --charset utf-8 -I "index.html" -P "*.html" -o ./index.html | sed -e '/<hr>/,+7d' > ./index.html

          git config --global user.name 'GH workflow'
          git config --global user.email ''
          git add ./index.html
          git commit -am "Automatically generated index.html file"
          git push -f

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_ROCK_07F745700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_ROCK_07F745700 }}
          action: "close"
