name: create index.html
on:
  workflow_dispatch:
    #This trigger helps show the "Run Workflow" button under the github actions page. Hence enabling to trigger workflow manually.
    #reference guide: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create index.html
        run: |
          sudo apt install tree
          pwd
          ls -l
          echo 'creating index.html file...'
          tree -H '.' -L 3 -r --noreport --charset utf-8 -P "*.html" -o ./index.html | sed -e '/<hr>/,+7d' > ./index.html
          ls -l
          
